### ISSUE TITLE
Template mod that uses Tau

### ISSUE THREAD

**Issue by Yarden-zamir** [mc-tau-ui/Tau#14]
**Describe the feature you'd like to see**
A simple template that we can just mess around with, test and extend.

**Describe feature use cases**
It will reduce friction of starting to use this

**Comment by winterSteve25** [comment]
Hey, thank you for your interest in Tau!

You can expect an update on this within the next few days.

**Comment by winterSteve25** [comment]
Hey I have been caught up by other stuff and haven't really had a chance to work on this. In the mean while, here are some simple instructions you can follow if you are trying to get started with it first yourself:

1. Get the version of forge mdk you want from [https://files.minecraftforge.net/net/minecraftforge/forge/](https://files.minecraftforge.net/net/minecraftforge/forge/)
2. Unzip what is downloaded
3. Add Tau as a dependency in build.gradle by adding 
```
maven { url = "https://maven.saps.dev/minecraft" }
```
to the repositories section and
```
implementation fg.deobf("com.github.wintersteve25:Tau:{version}")
```
to the dependencies section, replace {version} with the version you want, you can find them here [https://maven.saps.dev/#/releases/com/github/wintersteve25/Tau](https://maven.saps.dev/#/releases/com/github/wintersteve25/Tau)

**Comment by winterSteve25** [comment]
Templates can now be found at [https://github.com/mc-tau-ui/templates](https://github.com/mc-tau-ui/templates)
